### ISSUE TITLE
Simplify _foundation-icons.scss?

### ISSUE THREAD

**Issue by imsadhappy** [zurb/foundation-icon-fonts#17]
Hi. A question concerning _foundation-icons.scss.

Why not use CSS `[attribute^=value]` selector, rather than enumerate all the `.fi-[icon]:before` (from line 20 to line 302)? The specification on [w3school](http://www.w3schools.com/cssref/sel_attr_begin.asp) for this is quite clear. The support is down to IE7.

Like this:

``` css
[class^="fi-"]:before {
font-family: "foundation-icons";
font-style: normal;
font-weight: normal;
font-variant: normal;
text-transform: none;
line-height: 1;
-webkit-font-smoothing: antialiased;
display: inline-block;
text-decoration: inherit;
}
```
